{
 "title": "Homelab",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE cpu !~ /cpu-total/"
   },
   {
    "name": "idrac_host",
    "query": "SHOW TAG VALUES FROM \"idrac-hosts\" WITH KEY=\"system-name\""
   },
   {
    "name": "vcenter",
    "label": "vCenter Server",
    "query": "SHOW TAG VALUES FROM vsphere_host_cpu WITH KEY=vcenter"
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": "SHOW TAG VALUES FROM vsphere_datastore_disk WITH KEY=source WHERE \"vcenter\" =~ /$vcenter/"
   },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": "SHOW TAG VALUES FROM vsphere_host_cpu WITH KEY=clustername WHERE \"vcenter\" =~ /$vcenter/"
   },
   {
    "name": "pfsense",
    "label": "PfSense",
    "query": "SHOW TAG VALUES FROM cpu WITH KEY=host"
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 } },
  { "title": "Cluster overview", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 5, "y": 0 } },
  { "title": "Datastores", "type": "text", "gridPos": { "h": 1, "w": 7, "x": 17, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_sys",
     "select": [
      [
       { "params": [ "uptime_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CPU usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_sys",
     "query": "SELECT count(distinct(\"clustername\")) AS \"Clusters\" FROM (SELECT \"totalmhz_average\", \"clustername\" FROM  \"vsphere_cluster_cpu\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "uptime_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "clustername", "operator": "=", "value": "Lab-Cluster" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_sys",
     "query": "SELECT count(distinct(\"vmname\")) AS \"VMs\" FROM (SELECT \"usage_average\", \"vmname\" FROM  \"vsphere_vm_cpu\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "uptime_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "clustername", "operator": "=", "value": "Lab-Cluster" }
     ]
    }
   ]
  },
  {
   "title": "Datastore usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_source",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore_disk",
     "query": "SELECT last(\"used_latest\") * (100 / last(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($__interval) , \"source\"  fill(none)",
     "select": [
      [
       { "params": [ "used_latest" ], "type": "field" },
       { "params": [ "100 / last(capacity_latest)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$datastore$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_cluster_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RAM usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_sys",
     "query": "SELECT count(distinct(\"esxhostname\")) AS \"ESXi hosts\" FROM (SELECT \"coreUtilization_average\", \"esxhostname\" FROM  \"vsphere_host_cpu\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "uptime_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "clustername", "operator": "=", "value": "Lab-Cluster" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_sys",
     "query": "SELECT count(distinct(\"dsname\")) AS \"Datastores\" FROM (SELECT \"capacity_latest\", \"dsname\" FROM  \"vsphere_datastore_disk\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "uptime_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "clustername", "operator": "=", "value": "Lab-Cluster" }
     ]
    }
   ]
  },
  {
   "title": "Cluster CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "percent", "label": "Usage Average %" }
   ],
   "targets": [
    {
     "alias": "$tag_clustername",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "query": "SELECT last(\"usagemhz_average\") FROM \"vsphere_host_cpu\" WHERE (\"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval), \"clustername\" fill(none)",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster RAM Usage in %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "percent", "label": "Usage Average %" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "query": "SELECT last(\"totalCapacity_average\") * (last(\"usage_average\")) / 100 * 1024 FROM \"vsphere_host_mem\" WHERE  (\"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval), \"clustername\"  fill(none)",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vcenter", "operator": "=", "value": "vce-01.lab.local" },
      { "condition": "AND", "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Storage Adapter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 7 },
   "yaxes": [
    { "format": "ms", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_clustername - ReadAverage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_storageAdapter",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "totalReadLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "alias": "$tag_clustername - WriteAverage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_storageAdapter",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "totalWriteLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  { "title": "Climate", "type": "text", "gridPos": { "h": 1, "w": 14, "x": 0, "y": 12 } },
  {
   "title": "System Overview",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "idrac-url" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "SELECT \"bios-version\" FROM \"idrac-hosts\" WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter GROUP BY \"system-name\" LIMIT 1",
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-model" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "power-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "climate",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 3, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "climate",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Services", "type": "text", "gridPos": { "h": 1, "w": 10, "x": 14, "y": 16 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "climate",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "pfs-01.lab.local",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.0.0.2" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "dns-01.lab.local",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.0.0.10" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "dns-02.lab.local",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.0.0.11" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "mc-01.lab.local",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.0.0.31" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "web-01.lab.local",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.0.0.41" }
     ]
    }
   ]
  },
  { "title": "PfSense", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Active Users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"n_users\") FROM \"system\" WHERE (\"host\" = 'PFS-01.lab.local') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_users" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$pfsense$/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 3, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$pfsense$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$CPU$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "WAN in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "/8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$pfsense$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "pppoe0" }
     ]
    },
    {
     "alias": "WAN out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "/8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$pfsense$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "pppoe0" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "LAN in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "/8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$pfsense$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "vmx1" }
     ]
    },
    {
     "alias": "LAN out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "/8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$pfsense$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "vmx1" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Uptime",
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$pfsense$/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 3, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Memory usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$pfsense$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "System load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$pfsense$/" }
     ]
    }
   ]
  },
  { "title": "idrac-01", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "System uptime",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Global status",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Power state",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "power-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Service tag",
     "measurement": "idrac-hosts",
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Inlet Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "inlet-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "alias": "Exhaust Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "exhaust-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "CPU Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "PSU status",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "psu-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temperature status",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temp-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RAID Battery",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "raid-batterystate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "BIOS version",
     "measurement": "idrac-hosts",
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bios-version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Storage status",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "storage-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RAM status",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "memory-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CMOS battery",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "temp-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Intrusion",
     "measurement": "idrac-hosts",
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "intrusion-sensor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Power (W)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-watts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.30.102" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "RPM" }
   ],
   "targets": [
    {
     "alias": "Fan 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan1-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "alias": "Fan 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan2-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "alias": "Fan 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan3-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "alias": "Fan 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan4-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "alias": "Fan 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan5-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "alias": "Fan 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan6-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "alias": "Fan 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan7-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "title": "OS Information",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-osname" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-osversion" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "title": "System Log Entries",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 9, "x": 8, "y": 47 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "SELECT \"log-dates\" FROM \"idrac-hosts\" WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter GROUP BY \"log-number\" LIMIT 1",
     "select": [
      [
       { "params": [ "log-dates" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "log-entry" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "log-severity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk Status",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 47 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-capacity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-predictivefail" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-vendor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-current_mac" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-01" }
     ]
    }
   ]
  },
  { "title": "idrac-02", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "System uptime",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Global status",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Power state",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "power-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Service tag",
     "measurement": "idrac-hosts",
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Inlet Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "inlet-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "alias": "Exhaust Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "exhaust-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "CPU Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Storage status",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "storage-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temperature status",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temp-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RAID Battery",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "raid-batterystate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "BIOS version",
     "measurement": "idrac-hosts",
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bios-version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "PSU status",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "psu-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RAM status",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "memory-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CMOS battery",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "temp-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Intrusion",
     "measurement": "idrac-hosts",
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "intrusion-sensor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Power (W)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-watts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.30.103" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "none", "label": "RPM" }
   ],
   "targets": [
    {
     "alias": "Fan 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan1-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "alias": "Fan 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan2-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "alias": "Fan 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan3-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "alias": "Fan 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan4-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "alias": "Fan 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan5-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "alias": "Fan 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan6-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "alias": "Fan 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan7-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "title": "OS Information",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 75 },
   "targets": [
    {
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-osname" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-osversion" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "title": "System Log Entries",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 9, "x": 8, "y": 75 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "SELECT \"log-dates\" FROM \"idrac-hosts\" WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter GROUP BY \"log-number\" LIMIT 1",
     "select": [
      [
       { "params": [ "log-dates" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "log-entry" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "log-severity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk Status",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 75 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-capacity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-predictivefail" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-vendor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-current_mac" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-02" }
     ]
    }
   ]
  }
 ]
}